---
title: "10-plotting_vital_rate_functions"
author: "Danny Foster"
date: "1/18/2022"
output: html_document
---

```{r}
# setup

library(here)
library(tidyverse)
library(posterior)
library(bayesplot)
# load observed data
pila_data = readRDS(here::here('02-data', '02-for_analysis', 'pila_training.rds'))

# load mcmc results
pila_fit = readRDS(here::here('02-data', '03-results', 'real_fits', 'pila.rds'))

samples = as_draws_df(pila_fit$draws())

betas_s = samples %>% select(contains('beta_s'))
betas_g = samples %>% select(contains('beta_g'))
betas_f = samples %>% select(contains('beta_f'))


```

# Posteriors vs Priors

## Survival

```{r}

beta_s_names =   
  data.frame(
      param = c('beta_s[1]', 'beta_s[2]', 'beta_s[3]', 'beta_s[4]', 'beta_s[5]',
                'beta_s[6]', 'beta_s[7]', 'beta_s[8]', 'beta_s[9]', 'beta_s[10]',
                'beta_s[11]', 'beta_s[12]'),
      data_name = c('intercept', 'dbh_m.init', 'fire', 
              'disease','ba_scaled', 'cwd_dep90_scaled', 
              'cwd_mean_scaled', 'dbh_fire', 
              'dbh_disease', 'dbh_ba', 'dbh_cwd90', 'dbh_cwdmean'),
      position = str_pad(1:12, width = 2, side = 'left', pad = '0'),
      pretty_name = 
          c('Intercept','DBH (m)','Fire','Disease','Basal Area',
            'CWD Departure','CWD Mean','DBH x Fire','DBH x Disease',
            'DBH x BA','DBH x CWD Dep.','DBH X CWD Mean'))

pretty_beta_s_labels = 
  beta_s_names$pretty_name
names(pretty_beta_s_labels) = beta_s_names$position
betas_s %>%
  rowid_to_column('iter') %>%
  pivot_longer(cols = c(-iter),
               names_to = 'param',
               values_to = 'value') %>%
  left_join(beta_s_names
    ) %>%
  ggplot(aes(x = value))+
  geom_density(lwd = 1)+
  geom_density(
    data = data.frame(prior = rnorm(n = 1000, mean = 0, sd = 5)),
    aes(x = prior),
    color = 'red'
  )+
  geom_vline(xintercept = 0, color = 'grey', lty = 2, lwd = 1)+
  theme_minimal()+
  facet_wrap(~position, scales = 'free',
             labeller = 
               labeller(position = pretty_beta_s_labels))

samples %>%
  select(sigmaPlot_s) %>%
  ggplot(aes(x = sigmaPlot_s))+
  geom_density(lwd = 1)+
  geom_density(data = 
                 data.frame(prior = truncnorm::rtruncnorm(n = 1000, a = 0, mean = 0, sd = 5)),
               aes(x = prior), color = 'red')+
  theme_minimal()

samples %>%
  select(sigmaEco_s) %>%
  ggplot(aes(x = sigmaEco_s))+
  geom_density(lwd = 1)+
  geom_density(data = 
                 data.frame(prior = truncnorm::rtruncnorm(n = 1000, a = 0, mean = 0, sd = 5)),
               aes(x = prior), color = 'red')+
  theme_minimal()


```

## Growth

```{r}
beta_g_names =   
  data.frame(
      param = c('beta_g[1]', 'beta_g[2]', 'beta_g[3]', 'beta_g[4]', 'beta_g[5]',
                'beta_g[6]', 'beta_g[7]', 'beta_g[8]', 'beta_g[9]', 'beta_g[10]',
                'beta_g[11]', 'beta_g[12]'),
      data_name = c('intercept', 'dbh_m.init', 'fire', 
              'disease','ba_scaled', 'cwd_dep90_scaled', 
              'cwd_mean_scaled', 'dbh_fire', 
              'dbh_disease', 'dbh_ba', 'dbh_cwd90', 'dbh_cwdmean'),
      position = str_pad(1:12, width = 2, side = 'left', pad = '0'),
      pretty_name = 
          c('Intercept','DBH (m)','Fire','Disease','Basal Area',
            'CWD Departure','CWD Mean','DBH x Fire','DBH x Disease',
            'DBH x BA','DBH x CWD Dep.','DBH X CWD Mean'))

pretty_beta_g_labels = 
  beta_g_names$pretty_name
names(pretty_beta_g_labels) = beta_g_names$position

betas_g %>%
  rowid_to_column('iter') %>%
  pivot_longer(cols = c(-iter),
               names_to = 'param',
               values_to = 'value') %>%
  left_join(beta_g_names
    ) %>%
  ggplot(aes(x = value))+
  geom_density(lwd = 1)+
  geom_density(
    data = data.frame(prior = rnorm(n = 1000, mean = 0, sd = 5)),
    aes(x = prior),
    color = 'red'
  )+
  geom_vline(xintercept = 0, color = 'grey', lty = 2, lwd = 1)+
  theme_minimal()+
  facet_wrap(~position, scales = 'free',
             labeller = 
               labeller(position = pretty_beta_g_labels))

samples %>%
  select(sigmaPlot_g) %>%
  ggplot(aes(x = sigmaPlot_g))+
  geom_density(lwd = 1)+
  geom_density(data = 
                 data.frame(prior = truncnorm::rtruncnorm(n = 1000, a = 0, mean = 0, sd = 5)),
               aes(x = prior), color = 'red')+
  theme_minimal()

samples %>%
  select(sigmaEco_g) %>%
  ggplot(aes(x = sigmaEco_g))+
  geom_density(lwd = 1)+
  geom_density(data = 
                 data.frame(prior = truncnorm::rtruncnorm(n = 1000, a = 0, mean = 0, sd = 5)),
               aes(x = prior), color = 'red')+
  theme_minimal()

samples %>%
  select(sigmaEpsilon_g) %>%
  ggplot(aes(x = sigmaEpsilon_g))+
  geom_density(lwd = 1)+
  geom_density(data = 
                 data.frame(prior = truncnorm::rtruncnorm(n = 1000, a = 0, mean = 0, sd = 5)),
               aes(x = prior), color = 'red')+
  theme_minimal()

```

## Fecundity

```{r}
beta_f_names =   
  data.frame(
      param = c('beta_f[1]', 'beta_f[2]', 'beta_f[3]', 'beta_f[4]', 'beta_f[5]',
                'beta_f[6]', 'beta_f[7]', 'beta_f[8]', 'beta_f[9]', 'beta_f[10]',
                'beta_f[11]', 'beta_f[12]'),
      data_name = c('intercept', 'dbh_m.init', 'fire', 
              'disease','ba_scaled', 'cwd_dep90_scaled', 
              'cwd_mean_scaled', 'dbh_fire', 
              'dbh_disease', 'dbh_ba', 'dbh_cwd90', 'dbh_cwdmean'),
      position = str_pad(1:12, width = 2, side = 'left', pad = '0'),
      pretty_name = 
          c('Intercept','DBH (m)','Fire','Disease','Basal Area',
            'CWD Departure','CWD Mean','DBH x Fire','DBH x Disease',
            'DBH x BA','DBH x CWD Dep.','DBH X CWD Mean'))

pretty_beta_f_labels = 
  beta_f_names$pretty_name
names(pretty_beta_f_labels) = beta_f_names$position

betas_f %>%
  rowid_to_column('iter') %>%
  pivot_longer(cols = c(-iter),
               names_to = 'param',
               values_to = 'value') %>%
  left_join(beta_f_names
    ) %>%
  ggplot(aes(x = value))+
  geom_density(lwd = 1)+
  geom_density(
    data = data.frame(prior = rnorm(n = 1000, mean = 0, sd = 5)),
    aes(x = prior),
    color = 'red'
  )+
  geom_vline(xintercept = 0, color = 'grey', lty = 2, lwd = 1)+
  theme_minimal()+
  facet_wrap(~position, scales = 'free',
             labeller = 
               labeller(position = pretty_beta_f_labels))

half_cauchy_samples = 
  sapply(X = 1:1000,
         FUN = function(i){
           sample = 0
           while(sample<=0){
            sample = rcauchy(n = 1, location = 0, scale = 5)
           }
           return(sample)
         })

samples %>%
  select(kappa_r) %>%
  ggplot(aes(x = kappa_r))+
  geom_density(lwd = 1)+
  theme_minimal()+
  geom_density(
    data = data.frame(prior = half_cauchy_samples),
    aes(x = prior), 
    color = 'red'
  )

```


# Plotting parameters

## Survival

```{r}
mcmc_intervals(samples,
               pars = c('beta_s[1]',
                        'beta_s[2]',
                        'beta_s[3]',
                        'beta_s[4]',
                        'beta_s[5]',
                        'beta_s[6]',
                        'beta_s[7]',
                        'beta_s[8]',
                        'beta_s[9]',
                        'beta_s[10]',
                        'beta_s[11]',
                        'beta_s[12]',
                        'sigmaPlot_s',
                        'sigmaEco_s'))


```

Significant effects:

  - Intercept (+)
  - Size (+)
  - Fire (-)
  - Basal area (+)
  - CWD Departure (-)
  - Size X Fire (+)
  - Size X BA (-)

## Growth


```{r}

mcmc_intervals(samples,
               pars = c('beta_g[1]',
                        'beta_g[2]',
                        'beta_g[3]',
                        'beta_g[4]',
                        'beta_g[5]',
                        'beta_g[6]',
                        'beta_g[7]',
                        'beta_g[8]',
                        'beta_g[9]',
                        'beta_g[10]',
                        'beta_g[11]',
                        'beta_g[12]',
                        'sigmaPlot_g',
                        'sigmaEco_g',
                        'sigmaEpsilon_g'))


mcmc_intervals(samples,
               pars = c('beta_g[1]',
                        'beta_g[3]',
                        'beta_g[4]',
                        'beta_g[5]',
                        'beta_g[6]',
                        'beta_g[7]',
                        'beta_g[8]',
                        'beta_g[9]',
                        'beta_g[10]',
                        'beta_g[11]',
                        'beta_g[12]',
                        'sigmaPlot_g',
                        'sigmaEco_g',
                        'sigmaEpsilon_g'))


```

## Fecundity

```{r}
mcmc_intervals(samples,
               pars = c('beta_f[1]',
                        'beta_f[2]',
                        'beta_f[3]',
                        'beta_f[4]',
                        'beta_f[5]',
                        'beta_f[6]',
                        'beta_f[7]',
                        'beta_f[8]',
                        'beta_f[9]',
                        'beta_f[10]',
                        'beta_f[11]',
                        'beta_f[12]',
                        'sigmaPlot_f',
                        'sigmaEco_f'))

mcmc_intervals(samples, pars = 'kappa_r')


```

# Fixed Effects Counterfactuals

## Survival

```{r}

predict_survival_fixeff = 
  function(dataset){
    do.call('rbind',
            lapply(X = 1:4000,
                   FUN = function(i){
                     
                     beta_i = as.numeric(betas_s[i,])
                     
                     X = dataset[,c('intercept', 'dbh_m.init', 'fire', 
                                    'disease', 'ba_scaled', 
                                    'cwd_dep90_scaled', 'cwd_mean_scaled', 
                                    'dbh_fire', 'dbh_disease',
                                    'dbh_ba', 'dbh_cwd90', 'dbh_cwdmean')]
                     
                     predictions = X
                     predictions$logitp = 
                       as.numeric(as.matrix(X) %*% beta_i)
                     predictions$p = boot::inv.logit(predictions$logitp)
                     return(predictions)
                     
                   }))
    
  }

# first, "main effects" (other than the focal variable, disturbances held at false 
# and continuous variables held at 0 (other than size, they are scaled) 

## size main effect (no disturbances, continuous variables held at 0, which is 
## the subplot-level mean (so like the average subplot))
expand.grid('intercept' = 1,
            'dbh_m.init' = seq(from = 0.1, to = 1.25, by = 0.01),
            'fire' = 0,
            'disease' = 0,
            'ba_scaled' = 0,
            'cwd_dep90_scaled' = 0,
            'cwd_mean_scaled' = 0) %>%
  mutate(dbh_fire = dbh_m.init*fire,
         dbh_disease = dbh_m.init*disease,
         dbh_ba = dbh_m.init*ba_scaled,
         dbh_cwd90 = dbh_m.init*cwd_dep90_scaled,
         dbh_cwdmean = dbh_m.init*cwd_mean_scaled) %>%
  predict_survival_fixeff() %>%
  group_by(intercept, dbh_m.init, fire, disease, ba_scaled, 
           cwd_dep90_scaled, cwd_mean_scaled, dbh_fire, dbh_disease,
           dbh_ba, dbh_cwd90, dbh_cwdmean) %>%
  summarise(p.median = median(p),
            p.025 = quantile(p, probs = 0.025),
            p.25 = quantile(p, probs = 0.25),
            p.75 = quantile(p, probs = 0.75),
            p.975 = quantile(p, probs = 0.975)) %>%
  ggplot(data = .,
         aes(x = dbh_m.init))+
  geom_ribbon(aes(ymin = p.025, ymax = p.975),
              color = NA, alpha = 0.1)+
  geom_ribbon(aes(ymin = p.25, ymax = p.75),
              color = NA, alpha = 0.25)+
  geom_line(aes(y = p.median), lwd = 1.5)+
  scale_y_continuous(limits = c(0, 1))+
  theme_minimal()+
  labs(y = 'Predicted Survival')

# size X fire
expand.grid('intercept' = 1,
            'dbh_m.init' = seq(from = 0.1, to = 1.25, by = 0.01),
            'fire' = c(0,1),
            'disease' = 0,
            'ba_scaled' = 0,
            'cwd_dep90_scaled' = 0,
            'cwd_mean_scaled' = 0) %>%
  mutate(dbh_fire = dbh_m.init*fire,
         dbh_disease = dbh_m.init*disease,
         dbh_ba = dbh_m.init*ba_scaled,
         dbh_cwd90 = dbh_m.init*cwd_dep90_scaled,
         dbh_cwdmean = dbh_m.init*cwd_mean_scaled) %>%
  predict_survival_fixeff() %>%
  group_by(intercept, dbh_m.init, fire, disease, ba_scaled, 
           cwd_dep90_scaled, cwd_mean_scaled, dbh_fire, dbh_disease,
           dbh_ba, dbh_cwd90, dbh_cwdmean) %>%
  summarise(p.median = median(p),
            p.025 = quantile(p, probs = 0.025),
            p.25 = quantile(p, probs = 0.25),
            p.75 = quantile(p, probs = 0.75),
            p.975 = quantile(p, probs = 0.975)) %>%
  ggplot(data = .,
         aes(x = dbh_m.init, color = as.factor(fire)))+
  geom_ribbon(aes(ymin = p.025, ymax = p.975, fill = as.factor(fire)),
              color = NA, alpha = 0.1)+
  geom_ribbon(aes(ymin = p.25, ymax = p.75, fill = as.factor(fire)),
              color = NA, alpha = 0.25)+
  geom_line(aes(y = p.median), lwd = 1.5)+
  #scale_y_continuous(limits = c(0, 1))+
  scale_color_viridis_d(begin = 0.05, end = 0.85)+
  scale_fill_viridis_d(begin = 0.05, end = 0.85)+
  theme_minimal()+
  labs(y = 'Predicted Survival',
       fill = 'Fire',
       color = 'Fire',
       x = 'DBH (m)')

# size X disease
expand.grid('intercept' = 1,
            'dbh_m.init' = seq(from = 0.1, to = 1.25, by = 0.01),
            'fire' = 0,
            'disease' = c(0,1),
            'ba_scaled' = 0,
            'cwd_dep90_scaled' = 0,
            'cwd_mean_scaled' = 0) %>%
  mutate(dbh_fire = dbh_m.init*fire,
         dbh_disease = dbh_m.init*disease,
         dbh_ba = dbh_m.init*ba_scaled,
         dbh_cwd90 = dbh_m.init*cwd_dep90_scaled,
         dbh_cwdmean = dbh_m.init*cwd_mean_scaled) %>%
  predict_survival_fixeff() %>%
  group_by(intercept, dbh_m.init, fire, disease, ba_scaled, 
           cwd_dep90_scaled, cwd_mean_scaled, dbh_fire, dbh_disease,
           dbh_ba, dbh_cwd90, dbh_cwdmean) %>%
  summarise(p.median = median(p),
            p.025 = quantile(p, probs = 0.025),
            p.25 = quantile(p, probs = 0.25),
            p.75 = quantile(p, probs = 0.75),
            p.975 = quantile(p, probs = 0.975)) %>%
  ggplot(data = .,
         aes(x = dbh_m.init, color = as.factor(disease)))+
  geom_ribbon(aes(ymin = p.025, ymax = p.975, fill = as.factor(disease)),
              color = NA, alpha = 0.1)+
  geom_ribbon(aes(ymin = p.25, ymax = p.75, fill = as.factor(disease)),
              color = NA, alpha = 0.25)+
  geom_line(aes(y = p.median), lwd = 1.5)+
  #scale_y_continuous(limits = c(0, 1))+
  scale_color_viridis_d(begin = 0.05, end = 0.85)+
  scale_fill_viridis_d(begin = 0.05, end = 0.85)+
  theme_minimal()+
  labs(y = 'Predicted Survival',
       fill = 'Disease',
       color = 'Disease',
       x = 'DBH (m)')

# size X Basal area
expand.grid('intercept' = 1,
            'dbh_m.init' = seq(from = 0.1, to = 1.25, by = 0.01),
            'fire' = 0,
            'disease' = 0,
            'ba_scaled' = c(-1,0,1),
            'cwd_dep90_scaled' = 0,
            'cwd_mean_scaled' = 0) %>%
  mutate(dbh_fire = dbh_m.init*fire,
         dbh_disease = dbh_m.init*disease,
         dbh_ba = dbh_m.init*ba_scaled,
         dbh_cwd90 = dbh_m.init*cwd_dep90_scaled,
         dbh_cwdmean = dbh_m.init*cwd_mean_scaled) %>%
  predict_survival_fixeff() %>%
  group_by(intercept, dbh_m.init, fire, disease, ba_scaled, 
           cwd_dep90_scaled, cwd_mean_scaled, dbh_fire, dbh_disease,
           dbh_ba, dbh_cwd90, dbh_cwdmean) %>%
  summarise(p.median = median(p),
            p.025 = quantile(p, probs = 0.025),
            p.25 = quantile(p, probs = 0.25),
            p.75 = quantile(p, probs = 0.75),
            p.975 = quantile(p, probs = 0.975)) %>%
  ggplot(data = .,
         aes(x = dbh_m.init, color = as.factor(ba_scaled)))+
  geom_ribbon(aes(ymin = p.025, ymax = p.975, fill = as.factor(ba_scaled)),
              color = NA, alpha = 0.1)+
  geom_ribbon(aes(ymin = p.25, ymax = p.75, fill = as.factor(ba_scaled)),
              color = NA, alpha = 0.25)+
  geom_line(aes(y = p.median), lwd = 1.5)+
  #scale_y_continuous(limits = c(0, 1))+
  scale_color_viridis_d(begin = 0.05, end = 0.85)+
  scale_fill_viridis_d(begin = 0.05, end = 0.85)+
  theme_minimal()+
  labs(y = 'Predicted Survival',
       fill = 'Basal Area (scaled)',
       color = 'Basal Area (scaled)',
       x = 'DBH (m)')

# size X drought
expand.grid('intercept' = 1,
            'dbh_m.init' = seq(from = 0.1, to = 1.25, by = 0.01),
            'fire' = 0,
            'disease' = 0,
            'ba_scaled' = 0,
            'cwd_dep90_scaled' = c(-1,0,1),
            'cwd_mean_scaled' = 0) %>%
  mutate(dbh_fire = dbh_m.init*fire,
         dbh_disease = dbh_m.init*disease,
         dbh_ba = dbh_m.init*ba_scaled,
         dbh_cwd90 = dbh_m.init*cwd_dep90_scaled,
         dbh_cwdmean = dbh_m.init*cwd_mean_scaled) %>%
  predict_survival_fixeff() %>%
  group_by(intercept, dbh_m.init, fire, disease, ba_scaled, 
           cwd_dep90_scaled, cwd_mean_scaled, dbh_fire, dbh_disease,
           dbh_ba, dbh_cwd90, dbh_cwdmean) %>%
  summarise(p.median = median(p),
            p.025 = quantile(p, probs = 0.025),
            p.25 = quantile(p, probs = 0.25),
            p.75 = quantile(p, probs = 0.75),
            p.975 = quantile(p, probs = 0.975)) %>%
  ggplot(data = .,
         aes(x = dbh_m.init, color = as.factor(cwd_dep90_scaled)))+
  geom_ribbon(aes(ymin = p.025, ymax = p.975, fill = as.factor(cwd_dep90_scaled)),
              color = NA, alpha = 0.1)+
  geom_ribbon(aes(ymin = p.25, ymax = p.75, fill = as.factor(cwd_dep90_scaled)),
              color = NA, alpha = 0.25)+
  geom_line(aes(y = p.median), lwd = 1.5)+
  #scale_y_continuous(limits = c(0, 1))+
  scale_color_viridis_d(begin = 0.05, end = 0.85)+
  scale_fill_viridis_d(begin = 0.05, end = 0.85)+
  theme_minimal()+
  labs(y = 'Predicted Survival',
       fill = 'CWD Departure (scaled)',
       color = 'CWD Departure (scaled)',
       x = 'DBH (m)')

# size X dryness
expand.grid('intercept' = 1,
            'dbh_m.init' = seq(from = 0.1, to = 1.25, by = 0.01),
            'fire' = 0,
            'disease' = 0,
            'ba_scaled' = 0,
            'cwd_dep90_scaled' = 0,
            'cwd_mean_scaled' = c(-1,0,1)) %>%
  mutate(dbh_fire = dbh_m.init*fire,
         dbh_disease = dbh_m.init*disease,
         dbh_ba = dbh_m.init*ba_scaled,
         dbh_cwd90 = dbh_m.init*cwd_dep90_scaled,
         dbh_cwdmean = dbh_m.init*cwd_mean_scaled) %>%
  predict_survival_fixeff() %>%
  group_by(intercept, dbh_m.init, fire, disease, ba_scaled, 
           cwd_dep90_scaled, cwd_mean_scaled, dbh_fire, dbh_disease,
           dbh_ba, dbh_cwd90, dbh_cwdmean) %>%
  summarise(p.median = median(p),
            p.025 = quantile(p, probs = 0.025),
            p.25 = quantile(p, probs = 0.25),
            p.75 = quantile(p, probs = 0.75),
            p.975 = quantile(p, probs = 0.975)) %>%
  ggplot(data = .,
         aes(x = dbh_m.init, color = as.factor(cwd_mean_scaled)))+
  geom_ribbon(aes(ymin = p.025, ymax = p.975, fill = as.factor(cwd_mean_scaled)),
              color = NA, alpha = 0.1)+
  geom_ribbon(aes(ymin = p.25, ymax = p.75, fill = as.factor(cwd_mean_scaled)),
              color = NA, alpha = 0.25)+
  geom_line(aes(y = p.median), lwd = 1.5)+
  #scale_y_continuous(limits = c(0, 1))+
  scale_color_viridis_d(begin = 0.05, end = 0.85)+
  scale_fill_viridis_d(begin = 0.05, end = 0.85)+
  theme_minimal()+
  labs(y = 'Predicted Survival',
       fill = 'CWD Mean (scaled)',
       color = 'CWD Mean (scaled)',
       x = 'DBH (m)')


```

## Growth

```{r}

predict_grow_fixeff = 
  function(dataset){
    do.call('rbind',
            lapply(X = 1:4000,
                   FUN = function(i){
                     
                     beta_i = as.numeric(betas_g[i,])
                     
                     X = dataset[,c('intercept', 'dbh_m.init', 'fire', 
                                    'disease', 'ba_scaled', 
                                    'cwd_dep90_scaled', 'cwd_mean_scaled', 
                                    'dbh_fire', 'dbh_disease',
                                    'dbh_ba', 'dbh_cwd90', 'dbh_cwdmean')]
                     
                     predictions = X
                     predictions$size1 = 
                       as.numeric(as.matrix(X) %*% beta_i)
                     predictions$grow = 
                       predictions$size1-predictions$dbh_m.init
                     return(predictions)
                     
                   }))
    
  }
# first, "main effects" (other than the focal variable, disturbances held at false 
# and continuous variables held at 0 (other than size, they are scaled) 

## size main effect (no disturbances, continuous variables held at 0, which is 
## the subplot-level mean (so like the average subplot))
expand.grid('intercept' = 1,
            'dbh_m.init' = seq(from = 0.1, to = 1.25, by = 0.01),
            'fire' = 0,
            'disease' = 0,
            'ba_scaled' = 0,
            'cwd_dep90_scaled' = 0,
            'cwd_mean_scaled' = 0) %>%
  mutate(dbh_fire = dbh_m.init*fire,
         dbh_disease = dbh_m.init*disease,
         dbh_ba = dbh_m.init*ba_scaled,
         dbh_cwd90 = dbh_m.init*cwd_dep90_scaled,
         dbh_cwdmean = dbh_m.init*cwd_mean_scaled) %>%
  predict_grow_fixeff() %>%
  group_by(intercept, dbh_m.init, fire, disease, ba_scaled, 
           cwd_dep90_scaled, cwd_mean_scaled, dbh_fire, dbh_disease,
           dbh_ba, dbh_cwd90, dbh_cwdmean) %>%
  summarise(grow.median = median(grow),
            grow.025 = quantile(grow, probs = 0.025),
            grow.25 = quantile(grow, probs = 0.25),
            grow.75 = quantile(grow, probs = 0.75),
            grow.975 = quantile(grow, probs = 0.975)) %>%
  ggplot(data = .,
         aes(x = dbh_m.init))+
  geom_ribbon(aes(ymin = grow.025, ymax = grow.975),
              color = NA, alpha = 0.1)+
  geom_ribbon(aes(ymin = grow.25, ymax = grow.75),
              color = NA, alpha = 0.25)+
  geom_line(aes(y = grow.median), lwd = 1.5)+
  theme_minimal()+
  labs(y = 'Predicted DBH Growth (m)')

# size X fire
expand.grid('intercept' = 1,
            'dbh_m.init' = seq(from = 0.1, to = 1.25, by = 0.01),
            'fire' = c(0,1),
            'disease' = 0,
            'ba_scaled' = 0,
            'cwd_dep90_scaled' = 0,
            'cwd_mean_scaled' = 0) %>%
  mutate(dbh_fire = dbh_m.init*fire,
         dbh_disease = dbh_m.init*disease,
         dbh_ba = dbh_m.init*ba_scaled,
         dbh_cwd90 = dbh_m.init*cwd_dep90_scaled,
         dbh_cwdmean = dbh_m.init*cwd_mean_scaled) %>%
  predict_grow_fixeff() %>%
  group_by(intercept, dbh_m.init, fire, disease, ba_scaled, 
           cwd_dep90_scaled, cwd_mean_scaled, dbh_fire, dbh_disease,
           dbh_ba, dbh_cwd90, dbh_cwdmean) %>%
  summarise(grow.median = median(grow),
            grow.025 = quantile(grow, probs = 0.025),
            grow.25 = quantile(grow, probs = 0.25),
            grow.75 = quantile(grow, probs = 0.75),
            grow.975 = quantile(grow, probs = 0.975)) %>%
  ggplot(data = .,
         aes(x = dbh_m.init, color = as.factor(fire)))+
  geom_ribbon(aes(ymin = grow.025, ymax = grow.975, fill = as.factor(fire)),
              color = NA, alpha = 0.1)+
  geom_ribbon(aes(ymin = grow.25, ymax = grow.75, fill = as.factor(fire)),
              color = NA, alpha = 0.25)+
  geom_line(aes(y = grow.median), lwd = 1.5)+
  scale_color_viridis_d(begin = 0.05, end = 0.85)+
  scale_fill_viridis_d(begin = 0.05, end = 0.85)+
  theme_minimal()+
  labs(y = 'Predicted DBH Growth (m)',
       fill = 'Fire',
       color = 'Fire',
       x = 'DBH (m)')

# size X disease
expand.grid('intercept' = 1,
            'dbh_m.init' = seq(from = 0.1, to = 1.25, by = 0.01),
            'fire' = 0,
            'disease' = c(0,1),
            'ba_scaled' = 0,
            'cwd_dep90_scaled' = 0,
            'cwd_mean_scaled' = 0) %>%
  mutate(dbh_fire = dbh_m.init*fire,
         dbh_disease = dbh_m.init*disease,
         dbh_ba = dbh_m.init*ba_scaled,
         dbh_cwd90 = dbh_m.init*cwd_dep90_scaled,
         dbh_cwdmean = dbh_m.init*cwd_mean_scaled) %>%
  predict_grow_fixeff() %>%
  group_by(intercept, dbh_m.init, fire, disease, ba_scaled, 
           cwd_dep90_scaled, cwd_mean_scaled, dbh_fire, dbh_disease,
           dbh_ba, dbh_cwd90, dbh_cwdmean) %>%
  summarise(grow.median = median(grow),
            grow.025 = quantile(grow, probs = 0.025),
            grow.25 = quantile(grow, probs = 0.25),
            grow.75 = quantile(grow, probs = 0.75),
            grow.975 = quantile(grow, probs = 0.975)) %>%
  ggplot(data = .,
         aes(x = dbh_m.init, color = as.factor(disease)))+
  geom_ribbon(aes(ymin = grow.025, ymax = grow.975, fill = as.factor(disease)),
              color = NA, alpha = 0.1)+
  geom_ribbon(aes(ymin = grow.25, ymax = grow.75, fill = as.factor(disease)),
              color = NA, alpha = 0.25)+
  geom_line(aes(y = grow.median), lwd = 1.5)+
  #scale_y_continuous(limits = c(0, 1))+
  scale_color_viridis_d(begin = 0.05, end = 0.85)+
  scale_fill_viridis_d(begin = 0.05, end = 0.85)+
  theme_minimal()+
  labs(y = 'Predicted DBH Growth (m)',
       fill = 'Disease',
       color = 'Disease',
       x = 'DBH (m)')

# size X Basal area
expand.grid('intercept' = 1,
            'dbh_m.init' = seq(from = 0.1, to = 1.25, by = 0.01),
            'fire' = 0,
            'disease' = 0,
            'ba_scaled' = c(-1,0,1),
            'cwd_dep90_scaled' = 0,
            'cwd_mean_scaled' = 0) %>%
  mutate(dbh_fire = dbh_m.init*fire,
         dbh_disease = dbh_m.init*disease,
         dbh_ba = dbh_m.init*ba_scaled,
         dbh_cwd90 = dbh_m.init*cwd_dep90_scaled,
         dbh_cwdmean = dbh_m.init*cwd_mean_scaled) %>%
  predict_grow_fixeff() %>%
  group_by(intercept, dbh_m.init, fire, disease, ba_scaled, 
           cwd_dep90_scaled, cwd_mean_scaled, dbh_fire, dbh_disease,
           dbh_ba, dbh_cwd90, dbh_cwdmean) %>%
  summarise(grow.median = median(grow),
            grow.025 = quantile(grow, probs = 0.025),
            grow.25 = quantile(grow, probs = 0.25),
            grow.75 = quantile(grow, probs = 0.75),
            grow.975 = quantile(grow, probs = 0.975)) %>%
  ggplot(data = .,
         aes(x = dbh_m.init, color = as.factor(ba_scaled)))+
  geom_ribbon(aes(ymin = grow.025, ymax = grow.975, fill = as.factor(ba_scaled)),
              color = NA, alpha = 0.1)+
  geom_ribbon(aes(ymin = grow.25, ymax = grow.75, fill = as.factor(ba_scaled)),
              color = NA, alpha = 0.25)+
  geom_line(aes(y = grow.median), lwd = 1.5)+
  #scale_y_continuous(limits = c(0, 1))+
  scale_color_viridis_d(begin = 0.05, end = 0.85)+
  scale_fill_viridis_d(begin = 0.05, end = 0.85)+
  theme_minimal()+
  labs(y = 'Predicted DBH Growth (m)',
       fill = 'Basal Area (scaled)',
       color = 'Basal Area (scaled)',
       x = 'DBH (m)')

# size X drought
expand.grid('intercept' = 1,
            'dbh_m.init' = seq(from = 0.1, to = 1.25, by = 0.01),
            'fire' = 0,
            'disease' = 0,
            'ba_scaled' = 0,
            'cwd_dep90_scaled' = c(-1,0,1),
            'cwd_mean_scaled' = 0) %>%
  mutate(dbh_fire = dbh_m.init*fire,
         dbh_disease = dbh_m.init*disease,
         dbh_ba = dbh_m.init*ba_scaled,
         dbh_cwd90 = dbh_m.init*cwd_dep90_scaled,
         dbh_cwdmean = dbh_m.init*cwd_mean_scaled) %>%
  predict_grow_fixeff() %>%
  group_by(intercept, dbh_m.init, fire, disease, ba_scaled, 
           cwd_dep90_scaled, cwd_mean_scaled, dbh_fire, dbh_disease,
           dbh_ba, dbh_cwd90, dbh_cwdmean) %>%
  summarise(grow.median = median(grow),
            grow.025 = quantile(grow, probs = 0.025),
            grow.25 = quantile(grow, probs = 0.25),
            grow.75 = quantile(grow, probs = 0.75),
            grow.975 = quantile(grow, probs = 0.975)) %>%
  ggplot(data = .,
         aes(x = dbh_m.init, color = as.factor(cwd_dep90_scaled)))+
  geom_ribbon(aes(ymin = grow.025, ymax = grow.975, fill = as.factor(cwd_dep90_scaled)),
              color = NA, alpha = 0.1)+
  geom_ribbon(aes(ymin = grow.25, ymax = grow.75, fill = as.factor(cwd_dep90_scaled)),
              color = NA, alpha = 0.25)+
  geom_line(aes(y = grow.median), lwd = 1.5)+
  #scale_y_continuous(limits = c(0, 1))+
  scale_color_viridis_d(begin = 0.05, end = 0.85)+
  scale_fill_viridis_d(begin = 0.05, end = 0.85)+
  theme_minimal()+
  labs(y = 'Predicted DBH Growth (m)',
       fill = 'CWD Departure (scaled)',
       color = 'CWD Departure (scaled)',
       x = 'DBH (m)')

# size X dryness
expand.grid('intercept' = 1,
            'dbh_m.init' = seq(from = 0.1, to = 1.25, by = 0.01),
            'fire' = 0,
            'disease' = 0,
            'ba_scaled' = 0,
            'cwd_dep90_scaled' = 0,
            'cwd_mean_scaled' = c(-1,0,1)) %>%
  mutate(dbh_fire = dbh_m.init*fire,
         dbh_disease = dbh_m.init*disease,
         dbh_ba = dbh_m.init*ba_scaled,
         dbh_cwd90 = dbh_m.init*cwd_dep90_scaled,
         dbh_cwdmean = dbh_m.init*cwd_mean_scaled) %>%
  predict_grow_fixeff() %>%
  group_by(intercept, dbh_m.init, fire, disease, ba_scaled, 
           cwd_dep90_scaled, cwd_mean_scaled, dbh_fire, dbh_disease,
           dbh_ba, dbh_cwd90, dbh_cwdmean) %>%
  summarise(grow.median = median(grow),
            grow.025 = quantile(grow, probs = 0.025),
            grow.25 = quantile(grow, probs = 0.25),
            grow.75 = quantile(grow, probs = 0.75),
            grow.975 = quantile(grow, probs = 0.975)) %>%
  ggplot(data = .,
         aes(x = dbh_m.init, color = as.factor(cwd_mean_scaled)))+
  geom_ribbon(aes(ymin = grow.025, ymax = grow.975, fill = as.factor(cwd_mean_scaled)),
              color = NA, alpha = 0.1)+
  geom_ribbon(aes(ymin = grow.25, ymax = grow.75, fill = as.factor(cwd_mean_scaled)),
              color = NA, alpha = 0.25)+
  geom_line(aes(y = grow.median), lwd = 1.5)+
  #scale_y_continuous(limits = c(0, 1))+
  scale_color_viridis_d(begin = 0.05, end = 0.85)+
  scale_fill_viridis_d(begin = 0.05, end = 0.85)+
  theme_minimal()+
  labs(y = 'Predicted DBH Growth (m)',
       fill = 'CWD Mean (scaled)',
       color = 'CWD Mean (scaled)',
       x = 'DBH (m)')


```

## Fecundity

```{r}

predict_fecundity_fixeff = 
  function(dataset){
    do.call('rbind',
            lapply(X = 1:4000,
                   FUN = function(i){
                     
                     beta_i = as.numeric(betas_f[i,])
                     
                     X = dataset[,c('intercept', 'dbh_m.init', 'fire', 
                                    'disease', 'ba_scaled', 
                                    'cwd_dep90_scaled', 'cwd_mean_scaled', 
                                    'dbh_fire', 'dbh_disease',
                                    'dbh_ba', 'dbh_cwd90', 'dbh_cwdmean')]
                     
                     predictions = X
                     predictions$logf = 
                       as.numeric(as.matrix(X) %*% beta_i)
                     predictions$fecundity = 
                       exp(predictions$logf)
                     return(predictions)
                     
                   }))
    
  }
# first, "main effects" (other than the focal variable, disturbances held at false 
# and continuous variables held at 0 (other than size, they are scaled) 

## size main effect (no disturbances, continuous variables held at 0, which is 
## the subplot-level mean (so like the average subplot))
expand.grid('intercept' = 1,
            'dbh_m.init' = seq(from = 0.1, to = 1.25, by = 0.01),
            'fire' = 0,
            'disease' = 0,
            'ba_scaled' = 0,
            'cwd_dep90_scaled' = 0,
            'cwd_mean_scaled' = 0) %>%
  mutate(dbh_fire = dbh_m.init*fire,
         dbh_disease = dbh_m.init*disease,
         dbh_ba = dbh_m.init*ba_scaled,
         dbh_cwd90 = dbh_m.init*cwd_dep90_scaled,
         dbh_cwdmean = dbh_m.init*cwd_mean_scaled) %>%
  predict_fecundity_fixeff() %>%
  group_by(intercept, dbh_m.init, fire, disease, ba_scaled, 
           cwd_dep90_scaled, cwd_mean_scaled, dbh_fire, dbh_disease,
           dbh_ba, dbh_cwd90, dbh_cwdmean) %>%
  summarise(fecundity.median = median(fecundity),
            fecundity.025 = quantile(fecundity, probs = 0.025),
            fecundity.25 = quantile(fecundity, probs = 0.25),
            fecundity.75 = quantile(fecundity, probs = 0.75),
            fecundity.975 = quantile(fecundity, probs = 0.975)) %>%
  ggplot(data = .,
         aes(x = dbh_m.init))+
  geom_ribbon(aes(ymin = fecundity.025, ymax = fecundity.975),
              color = NA, alpha = 0.1)+
  geom_ribbon(aes(ymin = fecundity.25, ymax = fecundity.75),
              color = NA, alpha = 0.25)+
  geom_line(aes(y = fecundity.median), lwd = 1.5)+
  theme_minimal()+
  labs(y = 'Predicted Fecundity')

# size X fire
expand.grid('intercept' = 1,
            'dbh_m.init' = seq(from = 0.1, to = 1.25, by = 0.01),
            'fire' = c(0,1),
            'disease' = 0,
            'ba_scaled' = 0,
            'cwd_dep90_scaled' = 0,
            'cwd_mean_scaled' = 0) %>%
  mutate(dbh_fire = dbh_m.init*fire,
         dbh_disease = dbh_m.init*disease,
         dbh_ba = dbh_m.init*ba_scaled,
         dbh_cwd90 = dbh_m.init*cwd_dep90_scaled,
         dbh_cwdmean = dbh_m.init*cwd_mean_scaled) %>%
  predict_fecundity_fixeff() %>%
  group_by(intercept, dbh_m.init, fire, disease, ba_scaled, 
           cwd_dep90_scaled, cwd_mean_scaled, dbh_fire, dbh_disease,
           dbh_ba, dbh_cwd90, dbh_cwdmean) %>%
  summarise(fecundity.median = median(fecundity),
            fecundity.025 = quantile(fecundity, probs = 0.025),
            fecundity.25 = quantile(fecundity, probs = 0.25),
            fecundity.75 = quantile(fecundity, probs = 0.75),
            fecundity.975 = quantile(fecundity, probs = 0.975)) %>%
  ggplot(data = .,
         aes(x = dbh_m.init, color = as.factor(fire)))+
  geom_ribbon(aes(ymin = fecundity.025, ymax = fecundity.975, fill = as.factor(fire)),
              color = NA, alpha = 0.1)+
  geom_ribbon(aes(ymin = fecundity.25, ymax = fecundity.75, fill = as.factor(fire)),
              color = NA, alpha = 0.25)+
  geom_line(aes(y = fecundity.median), lwd = 1.5)+
  scale_color_viridis_d(begin = 0.05, end = 0.85)+
  scale_fill_viridis_d(begin = 0.05, end = 0.85)+
  theme_minimal()+
  labs(y = 'Predicted Fecundity',
       fill = 'Fire',
       color = 'Fire',
       x = 'DBH (m)')

# size X disease
expand.grid('intercept' = 1,
            'dbh_m.init' = seq(from = 0.1, to = 1.25, by = 0.01),
            'fire' = 0,
            'disease' = c(0,1),
            'ba_scaled' = 0,
            'cwd_dep90_scaled' = 0,
            'cwd_mean_scaled' = 0) %>%
  mutate(dbh_fire = dbh_m.init*fire,
         dbh_disease = dbh_m.init*disease,
         dbh_ba = dbh_m.init*ba_scaled,
         dbh_cwd90 = dbh_m.init*cwd_dep90_scaled,
         dbh_cwdmean = dbh_m.init*cwd_mean_scaled) %>%
  predict_fecundity_fixeff() %>%
  group_by(intercept, dbh_m.init, fire, disease, ba_scaled, 
           cwd_dep90_scaled, cwd_mean_scaled, dbh_fire, dbh_disease,
           dbh_ba, dbh_cwd90, dbh_cwdmean) %>%
  summarise(fecundity.median = median(fecundity),
            fecundity.025 = quantile(fecundity, probs = 0.025),
            fecundity.25 = quantile(fecundity, probs = 0.25),
            fecundity.75 = quantile(fecundity, probs = 0.75),
            fecundity.975 = quantile(fecundity, probs = 0.975)) %>%
  ggplot(data = .,
         aes(x = dbh_m.init, color = as.factor(disease)))+
  geom_ribbon(aes(ymin = fecundity.025, ymax = fecundity.975, fill = as.factor(disease)),
              color = NA, alpha = 0.1)+
  geom_ribbon(aes(ymin = fecundity.25, ymax = fecundity.75, fill = as.factor(disease)),
              color = NA, alpha = 0.25)+
  geom_line(aes(y = fecundity.median), lwd = 1.5)+
  #scale_y_continuous(limits = c(0, 1))+
  scale_color_viridis_d(begin = 0.05, end = 0.85)+
  scale_fill_viridis_d(begin = 0.05, end = 0.85)+
  theme_minimal()+
  labs(y = 'Predicted DBH Growth (m)',
       fill = 'Disease',
       color = 'Disease',
       x = 'DBH (m)')

# size X Basal area
expand.grid('intercept' = 1,
            'dbh_m.init' = seq(from = 0.1, to = 1.25, by = 0.01),
            'fire' = 0,
            'disease' = 0,
            'ba_scaled' = c(-1,0,1),
            'cwd_dep90_scaled' = 0,
            'cwd_mean_scaled' = 0) %>%
  mutate(dbh_fire = dbh_m.init*fire,
         dbh_disease = dbh_m.init*disease,
         dbh_ba = dbh_m.init*ba_scaled,
         dbh_cwd90 = dbh_m.init*cwd_dep90_scaled,
         dbh_cwdmean = dbh_m.init*cwd_mean_scaled) %>%
  predict_fecundity_fixeff() %>%
  group_by(intercept, dbh_m.init, fire, disease, ba_scaled, 
           cwd_dep90_scaled, cwd_mean_scaled, dbh_fire, dbh_disease,
           dbh_ba, dbh_cwd90, dbh_cwdmean) %>%
  summarise(fecundity.median = median(fecundity),
            fecundity.025 = quantile(fecundity, probs = 0.025),
            fecundity.25 = quantile(fecundity, probs = 0.25),
            fecundity.75 = quantile(fecundity, probs = 0.75),
            fecundity.975 = quantile(fecundity, probs = 0.975)) %>%
  ggplot(data = .,
         aes(x = dbh_m.init, color = as.factor(ba_scaled)))+
  geom_ribbon(aes(ymin = fecundity.025, ymax = fecundity.975, fill = as.factor(ba_scaled)),
              color = NA, alpha = 0.1)+
  geom_ribbon(aes(ymin = fecundity.25, ymax = fecundity.75, fill = as.factor(ba_scaled)),
              color = NA, alpha = 0.25)+
  geom_line(aes(y = fecundity.median), lwd = 1.5)+
  #scale_y_continuous(limits = c(0, 1))+
  scale_color_viridis_d(begin = 0.05, end = 0.85)+
  scale_fill_viridis_d(begin = 0.05, end = 0.85)+
  theme_minimal()+
  labs(y = 'Predicted DBH Growth (m)',
       fill = 'Basal Area (scaled)',
       color = 'Basal Area (scaled)',
       x = 'DBH (m)')

# size X drought
expand.grid('intercept' = 1,
            'dbh_m.init' = seq(from = 0.1, to = 1.25, by = 0.01),
            'fire' = 0,
            'disease' = 0,
            'ba_scaled' = 0,
            'cwd_dep90_scaled' = c(-1,0,1),
            'cwd_mean_scaled' = 0) %>%
  mutate(dbh_fire = dbh_m.init*fire,
         dbh_disease = dbh_m.init*disease,
         dbh_ba = dbh_m.init*ba_scaled,
         dbh_cwd90 = dbh_m.init*cwd_dep90_scaled,
         dbh_cwdmean = dbh_m.init*cwd_mean_scaled) %>%
  predict_fecundity_fixeff() %>%
  group_by(intercept, dbh_m.init, fire, disease, ba_scaled, 
           cwd_dep90_scaled, cwd_mean_scaled, dbh_fire, dbh_disease,
           dbh_ba, dbh_cwd90, dbh_cwdmean) %>%
  summarise(fecundity.median = median(fecundity),
            fecundity.025 = quantile(fecundity, probs = 0.025),
            fecundity.25 = quantile(fecundity, probs = 0.25),
            fecundity.75 = quantile(fecundity, probs = 0.75),
            fecundity.975 = quantile(fecundity, probs = 0.975)) %>%
  ggplot(data = .,
         aes(x = dbh_m.init, color = as.factor(cwd_dep90_scaled)))+
  geom_ribbon(aes(ymin = fecundity.025, ymax = fecundity.975, fill = as.factor(cwd_dep90_scaled)),
              color = NA, alpha = 0.1)+
  geom_ribbon(aes(ymin = fecundity.25, ymax = fecundity.75, fill = as.factor(cwd_dep90_scaled)),
              color = NA, alpha = 0.25)+
  geom_line(aes(y = fecundity.median), lwd = 1.5)+
  #scale_y_continuous(limits = c(0, 1))+
  scale_color_viridis_d(begin = 0.05, end = 0.85)+
  scale_fill_viridis_d(begin = 0.05, end = 0.85)+
  theme_minimal()+
  labs(y = 'Predicted DBH Growth (m)',
       fill = 'CWD Departure (scaled)',
       color = 'CWD Departure (scaled)',
       x = 'DBH (m)')

# size X dryness
expand.grid('intercept' = 1,
            'dbh_m.init' = seq(from = 0.1, to = 1.25, by = 0.01),
            'fire' = 0,
            'disease' = 0,
            'ba_scaled' = 0,
            'cwd_dep90_scaled' = 0,
            'cwd_mean_scaled' = c(-1,0,1)) %>%
  mutate(dbh_fire = dbh_m.init*fire,
         dbh_disease = dbh_m.init*disease,
         dbh_ba = dbh_m.init*ba_scaled,
         dbh_cwd90 = dbh_m.init*cwd_dep90_scaled,
         dbh_cwdmean = dbh_m.init*cwd_mean_scaled) %>%
  predict_fecundity_fixeff() %>%
  group_by(intercept, dbh_m.init, fire, disease, ba_scaled, 
           cwd_dep90_scaled, cwd_mean_scaled, dbh_fire, dbh_disease,
           dbh_ba, dbh_cwd90, dbh_cwdmean) %>%
  summarise(fecundity.median = median(fecundity),
            fecundity.025 = quantile(fecundity, probs = 0.025),
            fecundity.25 = quantile(fecundity, probs = 0.25),
            fecundity.75 = quantile(fecundity, probs = 0.75),
            fecundity.975 = quantile(fecundity, probs = 0.975)) %>%
  ggplot(data = .,
         aes(x = dbh_m.init, color = as.factor(cwd_mean_scaled)))+
  geom_ribbon(aes(ymin = fecundity.025, ymax = fecundity.975, fill = as.factor(cwd_mean_scaled)),
              color = NA, alpha = 0.1)+
  geom_ribbon(aes(ymin = fecundity.25, ymax = fecundity.75, fill = as.factor(cwd_mean_scaled)),
              color = NA, alpha = 0.25)+
  geom_line(aes(y = fecundity.median), lwd = 1.5)+
  #scale_y_continuous(limits = c(0, 1))+
  scale_color_viridis_d(begin = 0.05, end = 0.85)+
  scale_fill_viridis_d(begin = 0.05, end = 0.85)+
  theme_minimal()+
  labs(y = 'Predicted DBH Growth (m)',
       fill = 'CWD Mean (scaled)',
       color = 'CWD Mean (scaled)',
       x = 'DBH (m)')


```

